In [1]:
import numpy as np
import pandas as pd

In [4]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/vehicle_fuel.csv')
display(df.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,fuel_eff,cylinders,engine_size,horsepower,weight,acceleration,model_year,origin,car_name
0,8.3,8,6000,284,1739,16.7,2011,1,ford explorer
1,18.6,4,1740,94,1055,18.7,2019,2,bmw 520i
2,12.5,6,2800,141,1370,18.6,2021,1,buick lacrosse
3,10.3,8,4430,203,1635,19.2,2015,1,dodge dart
4,15.7,6,2790,129,1183,15.4,2021,1,chevrolet tahoe

Question 1
(a)

In [8]:
#Check if all attributes except car_name have a numeric data type
print(df.columns)
print(df.info())

Index(['fuel_eff', 'cylinders', 'engine_size', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'car_name'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   fuel_eff      320 non-null    float64
 1   cylinders     320 non-null    int64
 2   engine_size   320 non-null    int64
 3   horsepower    313 non-null    float64
 4   weight        320 non-null    int64
 5   acceleration  320 non-null    float64
 6   model_year    320 non-null    int64
 7   origin        320 non-null    category
 8   car_name      320 non-null    object
dtypes: category(1), float64(3), int64(4), object(1)
memory usage: 20.6+ KB
None

In [32]:
compact_summary = []
numeric_attribute = df.select_dtypes(include=[np.number]).columns

for row in numeric_attribute:
  meanVal = df[row].mean()
  medianVal = df[row].median()

  if meanVal != 0: #We are going to divide by the mean value so we have to check if it is not zero, to avoid division by zero.
    rel_diff = abs(meanVal - medianVal) / meanVal * 100
  else:
    rel_diff = 0.0

  if rel_diff > 10:
    verdict = "High"
  else:
    verdict = "Low"

  compact_summary.append({
      'Attribute': row,
      'Mean': round(meanVal, 2),
      'Median': round(medianVal, 2),
      'Deviation %': f"{round(rel_diff, 2)}%",
      'Verdict': verdict
  })

compact_summaryy = pd.DataFrame(compact_summary)
# Display the DataFrame hiding the index numbers on the left
display(compact_summaryy.style.hide(axis='index'))